# fly.toml app configuration file generated for dynamic-php on 2023-06-19T14:25:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dynamic-php"
primary_region = "yul"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
